units:
  # Proxy Spacing Variable
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      anchor:
        shift: [100, -200]    
      key:
        padding: 1ky
        spread: 1kx
      columns:
        lmacro:
          key.column_net: P1
          rows.mod.skip: true
        louter:
          key.column_net: P0
          rows.mod.skip: true
        lpinky:
          key.column_net: P2
          rows.mod.skip: true
        lring:
          key.column_net: P3
          rows.mod.skip: true
        lmiddle:
          key.column_net: P21
        lindex:
          key.column_net: P20
        linner:
          key.column_net: P19
        rinner:
          key.column_net: P18
          rows.function.skip: true
          rows.num.skip: true
        rindex:
          key.column_net: P15 
          rows.function.skip: true
          rows.num.skip: true
        rmiddle:
          key.column_net: P14
          rows.function.skip: true
          rows.num.skip: true
        rring:
          key.column_net: P16
          rows.function.skip: true
          rows.num.skip: true
          rows.mod.skip: true
        rpinky:
          key.column_net: P10
          rows.function.skip: true
          rows.num.skip: true
          rows.mod.skip: true
      rows:
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
        num:
          row_net: P5
        function:
          row_net: P4
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_lmacro_function
          shift: [-0.5px,1py]
        - ref: matrix_linner_function
          shift: [2px,1py]
        - ref: matrix_linner_top
          shift: [2px,0.5py]          
        - ref: matrix_rpinky_top
          shift: [0.5px,0.5py]          
        - ref: matrix_rpinky_bottom
          shift: [0.5px,-1.3py]
        - ref: matrix_rindex_mod
          shift: [0.5px,-0.5py]
        - ref: matrix_rinner_mod
          shift: [0.5px,-0.5py]
        - ref: matrix_linner_mod
          shift: [0.5px,-0.5py]
      
        - ref: matrix_lmacro_bottom
          shift: [-0.5px,-1.3py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  tutorial:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0,-5]
      promicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: matrix_rinner_top
          shift: [12,37.25]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_rinner_top
          shift: [-5,20.5]
          rotate: -90


